// INSERT INTO comments (task_id, user_id, body, parent_id) VALUES
//     (1, 1, 'Comment 1', NULL),
//     (1, 2, 'Comment 2', 1),
//     (1, 3, 'Comment 3', 2),
//     (2, 1, 'Comment 4', NULL),
//     (2, 2, 'Comment 5', 4),
//     (2, 3, 'Comment 6', 5),
//     (3, 1, 'Comment 7', NULL),
//     (3, 2, 'Comment 8', 7),
//     (3, 3, 'Comment 9', 8),
//     (4, 1, 'Comment 10', NULL),
//     (4, 2, 'Comment 11', 10),
//     (4, 3, 'Comment 12', 11),
//     (5, 1, 'Comment 13', NULL),
//     (5, 2, 'Comment 14', 13),
//     (5, 3, 'Comment 15', 14);

export const comments = [
  {
    id: 1,
    task_id: 1,
    user_id: 1,
    body: 'Comment 1',
    parent_id: null,
  },
  {
    id: 2,
    task_id: 1,
    user_id: 2,
    body: 'Comment 2',
    parent_id: 1,
  },
  {
    id: 3,
    task_id: 1,
    user_id: 3,
    body: 'Comment 3',
    parent_id: 2,
  },
  {
    id: 4,
    task_id: 2,
    user_id: 1,
    body: 'Comment 4',
    parent_id: null,
  },
  {
    id: 5,
    task_id: 2,
    user_id: 2,
    body: 'Comment 5',
    parent_id: 4,
  },
  {
    id: 6,
    task_id: 2,
    user_id: 3,
    body: 'Comment 6',
    parent_id: 5,
  },
  {
    id: 7,
    task_id: 3,
    user_id: 1,
    body: 'Comment 7',
    parent_id: null,
  },
  {
    id: 8,
    task_id: 3,
    user_id: 2,
    body: 'Comment 8',
    parent_id: 7,
  },
  {
    id: 9,
    task_id: 3,
    user_id: 3,
    body: 'Comment 9',
    parent_id: 8,
  },
  {
    id: 10,
    task_id: 4,
    user_id: 1,
    body: 'Comment 10',
    parent_id: null,
  },
  {
    id: 11,
    task_id: 4,
    user_id: 2,
    body: 'Comment 11',
    parent_id: 10,
  },
  {
    id: 12,
    task_id: 4,
    user_id: 3,
    body: 'Comment 12',
    parent_id: 11,
  },
  {
    id: 13,
    task_id: 5,
    user_id: 1,
    body: 'Comment 13',
    parent_id: null,
  },
  {
    id: 14,
    task_id: 5,
    user_id: 2,
    body: 'Comment 14',
    parent_id: 13,
  },
  {
    id: 15,
    task_id: 5,
    user_id: 3,
    body: 'Comment 15',
    parent_id: 14,
  },
];
