// INSERT INTO users (name, email, password, role) VALUES
//     ('admin1','admin1@gmail.com','adminpassword1','admin'),
//     ('admin2','admin2@gmail.com','adminpassword2','admin'),
//     ('admin3','admin3@gmail.com','adminpassword3','admin'),
//     ('manager1','manager1@gmail.com','managerpassword1','manager'),
//     ('manager2','manager2@gmail.com','managerpassword2','manager'),
//     ('manager3','manager3@gmail.com','managerpassword3','manager'),
//     ('developer1','developer1@gmail.com','developerpassword1','developer'),
//     ('developer2','developer2@gmail.com','developerpassword2','developer'),
//     ('developer3','developer3@gmail.com','developerpassword3','developer');

export const users = [
  {
    id: 1,
    name: 'admin1',
    email: 'admin1@gmail.com',
    password: 'AdminPass@1',
    role: 'admin',
  },
  {
    id: 2,
    name: 'admin2',
    email: 'admin2@gmail.com',
    password: 'AdminPass@2',
    role: 'admin',
  },
  {
    id: 3,
    name: 'admin3',
    email: 'admin3@gmail.com',
    password: 'AdminPass@3',
    role: 'admin',
  },
  {
    id: 4,
    name: 'manager1',
    email: 'manager1@gmail.com',
    password: 'ManagerPass@1',
    role: 'manager',
  },
  {
    id: 5,
    name: 'manager2',
    email: 'manager2@gmail.com',
    password: 'ManagerPass@2',
    role: 'manager',
  },
  {
    id: 6,
    name: 'manager3',
    email: 'manager3@gmail.com',
    password: 'ManagerPass@3',
    role: 'manager',
  },
  {
    id: 7,
    name: 'developer1',
    email: 'developer1@gmail.com',
    password: 'DeveloperPass@1',
    role: 'developer',
  },
  {
    id: 8,
    name: 'developer2',
    email: 'developer2@gmail.com',
    password: 'DeveloperPass@2',
    role: 'developer',
  },
  {
    id: 9,
    name: 'developer3',
    email: 'developer3@gmail.com',
    password: 'DeveloperPass@3',
    role: 'developer',
  },
];
